runtime: go111

env_variables:
  BUCKET_NAME: "word-storage"

handlers:
  - url: /
    script: auto
    secure: always
  - url: /word/new
    script: auto
    secure: always
  - url: /(.+)
    static_files: frontend/dist/\1
    upload: frontend/dist/.*
    secure: always

